  name: Deploy to Production

  on:
    workflow_dispatch:
      inputs:
        branch:
          description: 'Branch to deploy'
          required: true
          default: 'main'

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      permissions:
        contents: read
        pages: write
        id-token: write

      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.4.1' 

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application

        run: pnpm run build
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ vars.NEXT_PUBLIC_BASE_PATH }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
  
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment

        uses: actions/deploy-pages@v4

      - name: Display deployment URL

        run: echo "🚀 Deployment successful! URL:" "${{ steps.deployment.outputs.page_url }}"